esphome:
  name: switchplate

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "kiekeboe"

ota:
  password: "kiekeboe"

wifi:
  ssid: "LumenIOT24"
  password: "Lum3nS0fT"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Switchplate Fallback Hotspot"
    password: "70ydNiJZ44Ib"

captive_portal:
    

external_components:
    # use rtttl and dfplayer from ESPHome's dev branch in GitHub
    # equivalent shorthand for GitHub
    #- source: github://nielsnl68/SwitchPlate
    - source: 
       type: local
       path: C:\mos\NAS\development\PlatformIO\Projects\esphome-openhasp\components


switchplate:
    display: my display # Req
    id: abcname # Opt.
    pages:
      - id: myMainPage # Opt.
        name: myName
        selectable: true    # can be opened with next and previous page selectors
        objects:
          - type: button
            id: btnHello
            left: 10          # Opt. Horizontal position on the page
            top: 10           # Opt. Vertical position on the page
            width: 60         # Opt. Width of the object
            height: 20        # Opt. Height of the object
            toggle: false    # True: creates a toggle-on/toggle-off button. False: creates a normal button
            #state: 0         # 0 = untoggled, 1 = toggled
            text: "Hello "         # The text of the label
            align: left      # Text alignment: left, center, right
            text_mode: expand     # The wrapping mode of long text labels
